package com.designsystem.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8D4E2B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDBCB)
val onPrimaryContainerLight = Color(0xFF341100)
val secondaryLight = Color(0xFF765849)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBCB)
val onSecondaryContainerLight = Color(0xFF2B160B)
val tertiaryLight = Color(0xFF646031)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFECE4AA)
val onTertiaryContainerLight = Color(0xFF1F1C00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF221A15)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF221A15)
val surfaceVariantLight = Color(0xFFF4DED4)
val onSurfaceVariantLight = Color(0xFF52443D)
val outlineLight = Color(0xFF85736C)
val outlineVariantLight = Color(0xFFD7C2B9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E2A)
val inverseOnSurfaceLight = Color(0xFFFFEDE6)
val inversePrimaryLight = Color(0xFFFFB691)
val surfaceDimLight = Color(0xFFE8D7CF)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1EB)
val surfaceContainerLight = Color(0xFFFCEAE3)
val surfaceContainerHighLight = Color(0xFFF6E5DD)
val surfaceContainerHighestLight = Color(0xFFF0DFD8)

val primaryDark = Color(0xFFFFB691)
val onPrimaryDark = Color(0xFF542202)
val primaryContainerDark = Color(0xFF703716)
val onPrimaryContainerDark = Color(0xFFFFDBCB)
val secondaryDark = Color(0xFFE6BEAB)
val onSecondaryDark = Color(0xFF432B1E)
val secondaryContainerDark = Color(0xFF5C4032)
val onSecondaryContainerDark = Color(0xFFFFDBCB)
val tertiaryDark = Color(0xFFCFC890)
val onTertiaryDark = Color(0xFF353107)
val tertiaryContainerDark = Color(0xFF4C481C)
val onTertiaryContainerDark = Color(0xFFECE4AA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A120E)
val onBackgroundDark = Color(0xFFF0DFD8)
val surfaceDark = Color(0xFF1A120E)
val onSurfaceDark = Color(0xFFF0DFD8)
val surfaceVariantDark = Color(0xFF52443D)
val onSurfaceVariantDark = Color(0xFFD7C2B9)
val outlineDark = Color(0xFFA08D85)
val outlineVariantDark = Color(0xFF52443D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD8)
val inverseOnSurfaceDark = Color(0xFF382E2A)
val inversePrimaryDark = Color(0xFF8D4E2B)
val surfaceDimDark = Color(0xFF1A120E)
val surfaceBrightDark = Color(0xFF413732)
val surfaceContainerLowestDark = Color(0xFF140C09)
val surfaceContainerLowDark = Color(0xFF221A15)
val surfaceContainerDark = Color(0xFF271E19)
val surfaceContainerHighDark = Color(0xFF322823)
val surfaceContainerHighestDark = Color(0xFF3D332E)






