package com.designsystem.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFFFCB65)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD27E)
val onPrimaryContainerLight = Color(0xFF573D00)
val secondaryLight = Color(0xFF7A6B51)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF866757)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF57640F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD1E17F)
val onTertiaryContainerLight = Color(0xFF3C4700)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F3)
val onBackgroundLight = Color(0xFF1F1B14)
val surfaceLight = Color(0xFFFFF8F3)
val onSurfaceLight = Color(0xFF1F1B14)
val surfaceVariantLight = Color(0xFFEFE1CC)
val onSurfaceVariantLight = Color(0xFF4F4636)
val outlineLight = Color(0xFF817664)
val outlineVariantLight = Color(0xFFD2C5B1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF353028)
val inverseOnSurfaceLight = Color(0xFFF9EFE3)
val inversePrimaryLight = Color(0xFFF1BF5A)
val surfaceDimLight = Color(0xFFE2D9CD)
val surfaceBrightLight = Color(0xFFFFF8F3)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFCF2E6)
val surfaceContainerLight = Color(0xFFF6ECE1)
val surfaceContainerHighLight = Color(0xFFF1E7DB)
val surfaceContainerHighestLight = Color(0xFFEBE1D6)

val primaryDark = Color(0xFFFFF8F3)
val onPrimaryDark = Color(0xFF412D00)
val primaryContainerDark = Color(0xFFFBC762)
val onPrimaryContainerDark = Color(0xFF4F3800)
val secondaryDark = Color(0xFFE5BEAC)
val onSecondaryDark = Color(0xFF432B1E)
val secondaryContainerDark = Color(0xFF6B4E40)
val onSecondaryContainerDark = Color(0xFFFFF7F4)
val tertiaryDark = Color(0xFFF6FFBE)
val onTertiaryDark = Color(0xFF2C3400)
val tertiaryContainerDark = Color(0xFFC7D776)
val onTertiaryContainerDark = Color(0xFF364000)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF17130C)
val onBackgroundDark = Color(0xFFEBE1D6)
val surfaceDark = Color(0xFF17130C)
val onSurfaceDark = Color(0xFFEBE1D6)
val surfaceVariantDark = Color(0xFF4F4636)
val onSurfaceVariantDark = Color(0xFFD2C5B1)
val outlineDark = Color(0xFF9B8F7D)
val outlineVariantDark = Color(0xFF4F4636)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEBE1D6)
val inverseOnSurfaceDark = Color(0xFF353028)
val inversePrimaryDark = Color(0xFF7B5800)
val surfaceDimDark = Color(0xFF17130C)
val surfaceBrightDark = Color(0xFF3E3830)
val surfaceContainerLowestDark = Color(0xFF110E08)
val surfaceContainerLowDark = Color(0xFF1F1B14)
val surfaceContainerDark = Color(0xFF231F18)
val surfaceContainerHighDark = Color(0xFF2E2922)
val surfaceContainerHighestDark = Color(0xFF39342C)





